In [ ]:
import pandas as pd
from tqdm import tqdm
import numpy as np
from numpy import random as nr

df=pd.read_csv('C:/Users/xyttttt/Desktop/goodsale.csv',low_memory=False)
df=df.loc[df['data_date'] >= 20180201]
cols = [col for col in df.columns if col in['sku_id','goods_num']]
df = df.loc[:, cols]
df_group = df.groupby('sku_id')
df_mean = df_group.mean()
df_mean = df_mean*7

res = pd.read_csv('C:/Users/xyttttt/Desktop/submit_example.csv')
r,c = res.shape
for i in tqdm(range(r)):
    sku_id = res.iloc[i,0]
    if sku_id in df_mean.index:
        rand = nr.normal(0,0.3,size = (5,1))
        row=0;
        for k in df['sku_id']:
            if k==sku_id:
                row=row+1;
        for j in range(1,6):
            if row >= 30:
                res.iloc[i,j] = np.round((df_mean.loc[sku_id,'goods_num']+rand[j-1])*1.05).astype(int)#此权重在1-1.1之间效果较好
            elif row >= 17:
                res.iloc[i,j] = np.floor((df_mean.loc[sku_id,'goods_num']+rand[j-1])*0.72).astype(int)#此权重在0.7到0.75之间效果较好
            elif row >= 8:
                res.iloc[i,j] = np.floor((df_mean.loc[sku_id,'goods_num']+rand[j-1])*0.4).astype(int)#此权重在0.4-0.5之间效果较好
            else:
                res.iloc[i,j] = np.floor((df_mean.loc[sku_id,'goods_num']+rand[j-1])*0.2).astype(int)#此权重未调整
                
res.to_csv('C:/Users/xyttttt/Desktop/result.csv',index = False)
#918

In [3]:
import pandas as pd
from tqdm import tqdm
import numpy as np
from numpy import random as nr

res=pd.read_csv('C:/Users/xyttttt/Desktop/0918-2.csv',low_memory=False)

for i in tqdm(range(res.shape[0])):
    for j in range(1,6):
        if res.iloc[i,j]==0:
            res.iloc[i,j]=1
res

100%|██████████| 104510/104510 [10:21<00:00, 168.11it/s]

          sku_id  week1  week2  week3  week4  week5
0       SKDtK67I      2      2      2      2      2
1       SKpLKkIS      1      1      1      1      1
2       SK2vQMpX     10     10     10     10     10
3       SKY0RuBE      2      2      2      2      2
4       SKvr2o3y      1      1      1      1      1
5       SK4VKk3b      1      1      1      1      1
6       SKDbZjmX      1      1      1      1      1
7       SK9wkGUJ      1      1      1      1      1
8       SKjQriLy      1      1      1      1      1
9       SKGy1eQD      2      2      2      2      2
10      SKd8KLXp      1      1      1      1      1
11      SK6ry4mi      1      1      1      1      1
12      SKOpvNGo      3      3      3      3      3
13      SKMF0WaA      1      1      1      1      1
14      SKdm0HJM      1      1      1      1      1
15      SKBkZXdJ      1      1      1      1      1
16      SKSbGnOU      1      1      1      1      1
17      SKxSE825      1      1      1      1      1
18      SKAP7e14      1      1      1      1      1
19      SKPvgBf1      1      1      1      1      1
20      SKTJmOZN      4      4      4      4      4
21      SKTGcMxs      1      1      1      1      1
22      SKbr7XBs      1      1      1      1      1
23      SKXszyvc      1      1      1      1      1
24      SKA6jHsc      1      1      1      1      1
25      SKiKBu9I      2      2      2      2      2
26      SKhAngXl      1      1      1      1      1
27      SK4miVwF      1      1      1      1      1
28      SKwDEoBI      1      1      1      1      1
29      SKu5GlI2      1      1      1      1      1
...          ...    ...    ...    ...    ...    ...
104480  SKSTGMoi      2      2      2      2      2
104481  SKRCsoNG      1      1      1      1      1
104482  SKcM3X4W      1      1      1      1      1
104483  SKF0sfoM      1      1      1      1      1
104484  SKci9KdR      2      2      2      2      2
104485  SKCYWiD4      1      1      1      1      1
104486  SKNKRrLq      1      1      1      1      1
104487  SKcV6Nna     19     19     19     19     19
104488  SKDxZoCb      1      1      1      1      1
104489  SKJRToeW      4      4      4      4      4
104490  SKTGDCgO      1      1      1      1      1
104491  SKJ4PSHi      1      1      1      1      1
104492  SKY1ZEBx      1      1      1      1      1
104493  SKH4IZAX      1      1      1      1      1
104494  SKV2lWaq      1      1      1      1      1
104495  SKkjBRtA      1      1      1      1      1
104496  SKjc9p5X      1      1      1      1      1
104497  SKOtyXU2      1      1      1      1      1
104498  SKWot0jn      1      1      1      1      1
104499  SK12pAea      1      1      1      1      1
104500  SK8Jagpd      9      9      9      9      9
104501  SK0kXc7Z      1      1      1      1      1
104502  SK80MtVH      1      1      1      1      1
104503  SKIlvBf4      4      4      4      4      4
104504  SKdBKt4M      1      1      1      1      1
104505  SKteg3pG      1      1      1      1      1
104506  SKcE2nZk      1      1      1      1      1
104507  SKCjePQS      1      1      1      1      1
104508  SK0IHnm1      1      1      1      1      1
104509  SK4XSYtP      1      1      1      1      1

[104510 rows x 6 columns]

In [4]:
res.to_csv('C:/Users/xyttttt/Desktop/sample1.csv',index=False)